spring.application.name=Authentication

spring.datasource.url=jdbc:postgresql://localhost:5432/ghost
spring.datasource.username=postgres
spring.datasource.password=androidjava
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true